# Generated by Django 3.2.2 on 2021-05-08 18:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import wypozyczalnia_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Miasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=50)),
                ('pozycja', models.JSONField()),
            ],
            options={
                'verbose_name': 'Miasto',
                'verbose_name_plural': 'Miasta',
            },
        ),
        migrations.CreateModel(
            name='TypAuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100)),
                ('grafika', models.ImageField(upload_to=wypozyczalnia_app.models.path_typ_auta_ilustracja)),
                ('cena', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
            options={
                'verbose_name': 'Typ samochodu',
                'verbose_name_plural': 'Typy samochodów',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefon', models.DecimalField(decimal_places=0, max_digits=9)),
                ('karta', models.CharField(max_length=40)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Strefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rodzaj', models.CharField(choices=[('h', 'hulajnogowa'), ('s', 'samochodowa')], default='h', max_length=50)),
                ('lista_pozycji', models.JSONField(default={})),
                ('miasto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wypozyczalnia_app.miasto')),
            ],
            options={
                'verbose_name': 'Strefa',
                'verbose_name_plural': 'Strefy',
            },
        ),
        migrations.CreateModel(
            name='Samochod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pozycja', models.JSONField()),
                ('kolor', models.CharField(max_length=40)),
                ('marka', models.CharField(max_length=40)),
                ('model', models.CharField(max_length=40)),
                ('moc', models.DecimalField(decimal_places=1, max_digits=8)),
                ('nr_rejestracyjny', models.CharField(max_length=8)),
                ('paliwo', models.CharField(choices=[('b', 'benzyna'), ('d', 'diesel'), ('e', 'elektryczny'), ('h', 'hybryda'), ('g', 'LPG')], default='b', max_length=50)),
                ('wyposazenie', models.CharField(blank=True, max_length=200, null=True)),
                ('skrzynia_biegow', models.CharField(choices=[('a', 'automatyczna'), ('m', 'manualna')], default='m', max_length=30)),
                ('opis', models.CharField(blank=True, max_length=500, null=True)),
                ('image', models.ImageField(upload_to=wypozyczalnia_app.models.path_auta_img)),
                ('typ_wynajmu', models.CharField(choices=[('d', 'tługoterminowy'), ('k', 'krótkoterminowy')], default='d', max_length=30)),
                ('czy_wynajety', models.DateTimeField(blank=True, default=None, null=True)),
                ('zasieg', models.DecimalField(decimal_places=3, max_digits=8)),
                ('service', models.BooleanField(default=False)),
                ('kodQR', models.ImageField(upload_to=wypozyczalnia_app.models.path_kodQR_auto)),
                ('miasto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wypozyczalnia_app.miasto')),
                ('typ_auta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wypozyczalnia_app.typauta')),
            ],
            options={
                'verbose_name': 'Samochód',
                'verbose_name_plural': 'Samochody',
            },
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefon', models.DecimalField(decimal_places=0, max_digits=9)),
                ('karta', models.CharField(max_length=40)),
                ('pj_img', models.ImageField(upload_to=wypozyczalnia_app.models.path_prawa_jazdy)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Oddzial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pozycja', models.JSONField()),
                ('adres', models.CharField(max_length=100)),
                ('miasto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wypozyczalnia_app.miasto')),
            ],
            options={
                'verbose_name': 'Oddział',
                'verbose_name_plural': 'Oddziały',
            },
        ),
        migrations.CreateModel(
            name='Hulajnoga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pozycja', models.JSONField()),
                ('image', models.ImageField(upload_to=wypozyczalnia_app.models.path_hulajnogi_img)),
                ('cena', models.DecimalField(decimal_places=2, max_digits=8)),
                ('nr_identyfikacyjny', models.DecimalField(decimal_places=0, max_digits=8)),
                ('czy_wynajety', models.DateTimeField(default=None, null=True)),
                ('zasieg', models.DecimalField(decimal_places=3, max_digits=6)),
                ('service', models.BooleanField(default=False)),
                ('kodQR', models.ImageField(upload_to=wypozyczalnia_app.models.path_kodQR_hulajnogi)),
                ('miasto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wypozyczalnia_app.miasto')),
            ],
            options={
                'verbose_name': 'Hulajnoga',
                'verbose_name_plural': 'Hulajnogi',
            },
        ),
    ]
