# Generated by Django 3.2.2 on 2021-05-07 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Miasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=50)),
                ('pozycja', models.JSONField(default={})),
            ],
        ),
        migrations.CreateModel(
            name='Strefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rodzaj', models.CharField(max_length=50)),
                ('miasto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wypozyczalnia_app.miasto')),
            ],
        ),
    ]
