# Generated by Django 3.2.2 on 2021-05-08 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wypozyczalnia_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='telefon',
            field=models.CharField(max_length=40),
        ),
    ]
