# Generated by Django 3.2 on 2021-05-08 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wypozyczalnia_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samochod',
            name='typ_wynajmu',
            field=models.CharField(choices=[('d', 'długoterminowy'), ('k', 'krótkoterminowy')], default='d', max_length=30),
        ),
    ]
