# Generated by Django 3.2.2 on 2021-05-07 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wypozyczalnia_app', '0002_strefa_lista_pozycji'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='miasto',
            options={'verbose_name': 'Miasto', 'verbose_name_plural': 'Miasta'},
        ),
        migrations.AlterModelOptions(
            name='strefa',
            options={'verbose_name': 'Strefa', 'verbose_name_plural': 'Strefy'},
        ),
        migrations.CreateModel(
            name='Oddzial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pozycja', models.JSONField()),
                ('adres', models.CharField(max_length=100)),
                ('miasto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wypozyczalnia_app.miasto')),
            ],
            options={
                'verbose_name': 'Oddział',
                'verbose_name_plural': 'Oddziały',
            },
        ),
    ]
