# Generated by Django 3.2.2 on 2021-05-08 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wypozyczalnia_app', '0003_rename_telefon_userprofile_telefonkom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='telefon',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=9, null=True),
        ),
    ]
