# Generated by Django 3.2.2 on 2021-05-08 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wypozyczalnia_app', '0004_alter_profil_telefon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='karta',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='profil',
            name='telefon',
            field=models.CharField(max_length=9, null=True),
        ),
    ]
