# Generated by Django 3.2.2 on 2021-05-08 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wypozyczalnia_app', '0005_auto_20210508_1841'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
