# Generated by Django 3.2.2 on 2021-05-08 22:58

from django.db import migrations, models
import wypozyczalnia_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('wypozyczalnia_app', '0007_alter_profil_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='karta',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='profil',
            name='pj_img',
            field=models.ImageField(blank=True, null=True, upload_to=wypozyczalnia_app.models.path_prawa_jazdy),
        ),
        migrations.AlterField(
            model_name='profil',
            name='telefon',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
