# Generated by Django 3.2.2 on 2021-05-09 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wypozyczalnia_app', '0002_alter_samochod_typ_wynajmu'),
        ('wypozyczalnia_app', '0008_auto_20210508_2258'),
    ]

    operations = [
    ]
