# Generated by Django 3.2 on 2021-05-19 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wypozyczalnia_app', '0011_samochod_kod'),
    ]

    operations = [
        migrations.AddField(
            model_name='hulajnoga',
            name='kod',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
