# Generated by Django 3.2 on 2021-05-19 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wypozyczalnia_app', '0012_hulajnoga_kod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hulajnoga',
            name='czy_wynajety',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
