# Generated by Django 3.2 on 2021-05-20 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wypozyczalnia_app', '0014_zamowienia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zamowienia',
            options={'verbose_name': 'Zamówienie', 'verbose_name_plural': 'Zamówienia'},
        ),
        migrations.AlterField(
            model_name='zamowienia',
            name='czy_obecnie_wynajety',
            field=models.BooleanField(default=True),
        ),
    ]
