# Generated by Django 3.2.2 on 2021-05-20 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wypozyczalnia_app', '0015_auto_20210520_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zamowienia',
            name='kwota',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=8, null=True),
        ),
    ]
